{
	"version": 1511798377,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/play-sheet0.png",
		"images/mapa-sheet0.png",
		"images/player-sheet0.png",
		"images/death-sheet0.png",
		"images/bullet-sheet0.png",
		"images/enemy3-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/enemy-sheet0.png",
		"images/bulletexp-sheet0.png",
		"images/explosion-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/muteoff-sheet0.png",
		"images/muteon-sheet0.png",
		"media/bullet.m4a",
		"media/bullet.ogg",
		"media/eggbreak.m4a",
		"media/eggbreak.ogg",
		"media/uptown funk.ogg",
		"media/centuries (8 bit remix cover version) [tribute to fall out boy] - 8 bit universe.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}